ES_RAM_PERCENTAGE=${ES_RAM_PERCENTAGE:=75}
ES_INITIAL_RAM_PERCENTAGE="-XX:InitialRAMPercentage=${ES_RAM_PERCENTAGE}"
ES_MIN_RAM_PERCENTAGE="-XX:MinRAMPercentage=${ES_RAM_PERCENTAGE}"
ES_MAX_RAM_PERCENTAGE="-XX:MaxRAMPercentage=${ES_RAM_PERCENTAGE}"

export ES_JAVA_OPTS="${ES_INITIAL_RAM_PERCENTAGE} ${ES_MIN_RAM_PERCENTAGE} ${ES_MAX_RAM_PERCENTAGE} ${ES_JAVA_OPTS}"
